### ISSUE TITLE
Number the steps in solution

### ISSUE THREAD

**Issue by bnbarnes** [shlomif/fc-solve#17]
Sequentially number the steps in the solution. Easy to get lost when scrolling.

**Comment by shlomif** [comment]
@bnbarnes : hi! Do you mean in the web-based version ( http://fc-solve.shlomifish.org/js-fc-solve/text/ ) or in the output of the command line `fc-solve` executable?

**Comment by shlomif** [comment]
On Sun, 19 Aug 2018 12:22:19 -0700
bnbarnes <notifications@github.com> wrote:

> In the website. I haven’t looked at the executable. 
> 

ok, thanks for the clarification. This seems like a useful enhancement.

> Regards,
> Bruce
> Sent from my iPhone
> 
> > On Aug 19, 2018, at 12:01 PM, Shlomi Fish <notifications@github.com> wrote:
> > 
> > @bnbarnes : hi! Do you mean in the web-based version
> > ( http://fc-solve.shlomifish.org/js-fc-solve/text/ ) or in the output of
> > the command line fc-solve executable?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.  
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/shlomif/fc-solve/issues/17#issuecomment-414149577


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Free (Creative Commons) Music Downloads, Reviews and more - http://jamendo.com/

<Su-Shee> Absolutely. Also: a German dog barks “wau” and a cat meows “miau”
<rindolf> Su-Shee: German animals are true German patriots.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
This was implemented now in http://fc-solve.shlomifish.org/js-fc-solve/text/ - please let me know what you think. Thanks!

**Comment by shlomif** [comment]
@bnbarnes : just at-mentioning your nick,

**Comment by shlomif** [comment]
@bnbarnes : ping! Can I close this issue now?

**Comment by bnbarnes** [comment]
Yes 

Regards,
Bruce

**Comment by shlomif** [comment]
@bnbarnes : thanks! closing.
