### ISSUE TITLE
Convert cmake config to GNUInstallDirs

### ISSUE THREAD

**Issue by shlomif** [shlomif/fc-solve#36]
@a17r : hi, are you happy with the changes in this branch: https://github.com/shlomif/fc-solve/tree/cmake-gnu-install-dirs--feature-branch . Please review and tell me if you approve. Thanks!

**Comment by shlomif** [comment]
Thanks @a17r for reviewing my changes! I pushed new changesets to the branch based on your commentary.

**Comment by shlomif** [comment]
@a17r : hi! Do you have any further commentary on the changes here: https://github.com/shlomif/fc-solve/compare/master..cmake-gnu-install-dirs--feature-branch . May I merge them now?

**Comment by a17r** [comment]
looks good to me ;)

**Comment by shlomif** [comment]
@a17r : merged, thanks!
