### ISSUE TITLE
You tried to plan twice

### ISSUE THREAD

**Issue by eserte** [shlomif/fc-solve#39]
The test suite of Games-Solitaire-Verify-0.2301 fails on a few of my smoker systems:
```
You tried to plan twice at t/exception-newline.t line 11.
# Looks like your test exited with 2 before it could output anything.
t/exception-newline.t ..... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
```

**Comment by shlomif** [comment]
Thanks for the report! It should be fixed in 0.2302: https://github.com/shlomif/fc-solve/commit/f213d60f3fe282222156b6cf0855a40fb5e1b167 .

**Comment by shlomif** [comment]
On Mon, 20 Apr 2020 09:21:51 -0700
Slaven Rezić <notifications@github.com> wrote:

> The test suite of Games-Solitaire-Verify-0.2301 fails on a few of my smoker
> systems: ```
> You tried to plan twice at t/exception-newline.t line 11.
> # Looks like your test exited with 2 before it could output anything.
> t/exception-newline.t ..... 
> Dubious, test returned 2 (wstat 512, 0x200)
> Failed 2/2 subtests 
> ```
> 
> 

Thanks for the report - I intend to fix it.

-- 

Shlomi Fish       https://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - https://shlom.in/selina

Which is worse: ignorance or apathy?  Who knows?  Who cares?
    — Source unknown.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@eserte : since this is all green I am closing this ticket. Thanks! http://matrix.cpantesters.org/?dist=Games-Solitaire-Verify+0.2302
