### ISSUE TITLE
sscanf safety check

### ISSUE THREAD

**Issue by B1Z0N** [shlomif/fc-solve#91]
Hello, as I've seen in all of your `sscanf`'s(and other functions from this family) you are checking for return value and processing invalid data. There's only one exception there. It's [this](https://github.com/shlomif/fc-solve/blob/166010f76e44b3d4904bc42e66dce3b3d7f4706a/fc-solve/source/split_fcc_solver.c#L746) `sscanf`. 

As you know much more about design of this tool I kindly ask you to check if it's ok.

**Comment by shlomif** [comment]
@B1Z0N : thanks, fixed
