### ISSUE TITLE
cpanratings.perl.org no longer exists

### ISSUE THREAD

**Issue by pjacklam** [shlomif/fc-solve#95]
This distribution has a link to CPAN Ratings at cpanratings.perl.org, but this address now redirects to https://metacpan.org/

**Comment by shlomif** [comment]
@pjacklam : hi! Thanks for the reports, but see https://www.shlomifish.org/meta/FAQ/broken_links.xhtml and https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml (broken hyperlinks in the bible)
